# Generated by Django 5.0.3 on 2024-03-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id_pet', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('especie', models.TextField(max_length=255)),
                ('porte', models.TextField(max_length=255)),
                ('raca', models.TextField(max_length=255)),
                ('cor', models.TextField(max_length=255)),
                ('sexo', models.CharField(max_length=1)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.IntegerField()),
                ('cep', models.IntegerField()),
                ('endereco', models.TextField(max_length=255)),
                ('numero', models.IntegerField()),
                ('bairro', models.TextField(max_length=255)),
                ('cidade', models.TextField(max_length=255)),
                ('estado', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
                ('endereco', models.TextField(max_length=255)),
                ('numero', models.IntegerField()),
                ('bairro', models.TextField(max_length=255)),
                ('cidade', models.TextField(max_length=255)),
                ('estado', models.TextField(max_length=255)),
                ('telefone', models.TextField(max_length=255)),
                ('crmv', models.TextField(max_length=255)),
                ('senha', models.TextField(max_length=255)),
                ('confirmar_senha', models.TextField(max_length=255)),
            ],
        ),
    ]
