# Generated by Django 5.0.3 on 2024-03-30 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='João Pereira', max_length=200)),
                ('telefone', models.CharField(default='00 00000-0000', max_length=13)),
                ('cep', models.CharField(default='00000-000', max_length=8)),
                ('logradouro', models.CharField(default='Rua 10', max_length=200)),
                ('numero', models.CharField(default='00000', max_length=5)),
                ('complemento', models.CharField(default='', max_length=200)),
                ('bairro', models.CharField(default='Goiás', max_length=100)),
                ('cidade', models.CharField(default='Araras', max_length=100)),
                ('estado', models.CharField(default='SP', max_length=2)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='veterinario',
            name='bairro',
            field=models.CharField(default='São José', max_length=100),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='logradouro',
            field=models.CharField(default='Rua 1', max_length=200),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='telefone2',
            field=models.CharField(default='00 00000-0000', max_length=13),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='cidade',
            field=models.CharField(default='Araras', max_length=100),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='complemento',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='email',
            field=models.EmailField(default='joana.silva@gmail.com', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='nome',
            field=models.CharField(default='Joana da Silva', max_length=100),
        ),
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Bus', max_length=100)),
                ('especie', models.CharField(default='Canino', max_length=100)),
                ('porte', models.CharField(choices=[('PEQUENO', 'Pequeno'), ('MEDIO', 'Medio'), ('GRANDE', 'Grande')], max_length=20)),
                ('raca', models.CharField(default='Pastor Alemão', max_length=150)),
                ('cor', models.CharField(default='Preto', max_length=100)),
                ('sexo', models.CharField(choices=[('FEMININO', 'Feminino'), ('MASCULINO', 'Masculino')], max_length=10)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='ShopApp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicos', models.CharField(choices=[('BANHO_E_TOSA', 'Banho e Tosa'), ('TOSA_HIGIENICA', 'Tosa Higiênica'), ('HIDRATACAO', 'Hidratação'), ('VACINACAO', 'Vacinação'), ('EXAMES_LABORATORIAIS', 'Exames Laboratórias'), ('MICROCHIPAGEM', 'Microchipagem'), ('CONSULTA_CLINICA', 'Consulta Clínica'), ('ATENDIMENTO_DOMICILIAR', 'Atendimento Domiciliar'), ('ATENDIMENTO_24_HORAS', 'Atendimento 24 horas'), ('HOSPEDAGEM', 'Hospedagem'), ('TRANSPORTE', 'Transporte'), ('ADESTRAMENTO', 'Adestramento')], max_length=150)),
                ('servicos_personalizados', models.CharField(max_length=150)),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='ShopApp.veterinario')),
            ],
        ),
        migrations.AddField(
            model_name='veterinario',
            name='servicos_oferecidos',
            field=models.ManyToManyField(related_name='veterinarios', to='ShopApp.servicos'),
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_aplicacao', models.DateField()),
                ('proxima_dose', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas_aplicadas', to='ShopApp.animais')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas_aplicadas', to='ShopApp.veterinario')),
            ],
        ),
        migrations.AddField(
            model_name='animais',
            name='vacinas',
            field=models.ManyToManyField(related_name='animais_vacinados', to='ShopApp.vacina'),
        ),
        migrations.CreateModel(
            name='Vermifugos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('dose', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vermifugos_administrados', to='ShopApp.animais')),
            ],
        ),
        migrations.AddField(
            model_name='animais',
            name='vermifugos',
            field=models.ManyToManyField(related_name='animais_vermifugados', to='ShopApp.vermifugos'),
        ),
    ]
